name: Check actions
permissions: {}

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - "main"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
